marks = []
a=input("Enter marks:")
marks.append(a)
b=input("Enter  marks:")
marks.append(b)
c=input("Enter marks:")
marks.append(c)
d=input("Enter marks:")
marks.append(d)
e=input("Enter marks:")
marks.append(e)
print("Marks you entered:",marks)
marks.sort()  
print("The sorted marks are:",marks)